# Prometheus Config: Deployment Pods Only
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
    # 1. PROMETHEUS ITSELF - Minimal self-monitoring
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:9090']

    # 2. DEPLOYMENT PODS ONLY - Only pods created by Deployments
    - job_name: 'deployment-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      # FILTER 1: Only pods with prometheus.io/scrape=true annotation
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      
      # FILTER 2: Only pods owned by ReplicaSets (which are created by Deployments)
      - source_labels: [__meta_kubernetes_pod_controller_kind]
        action: keep
        regex: ReplicaSet
      
      # Set custom metrics path if specified (default: /metrics)
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
        
      # Set custom port if specified
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
        
      # Add useful labels for deployment pods
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
        
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
        
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
        
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: replace
        target_label: app_name
        
      # Extract deployment name from ReplicaSet name
      - source_labels: [__meta_kubernetes_pod_controller_name]
        regex: '(.+)-[a-f0-9]{8,10}'
        target_label: deployment_name
        replacement: '${1}'
        
      # Add container name
      - source_labels: [__meta_kubernetes_pod_container_name]
        action: replace
        target_label: container_name