apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "datasources": [
            {
                "name": "prometheus",
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring.svc.cluster.local:9090"
            }
        ]
    }