apiVersion: v1
kind: Service
metadata:
  name: backend-metrics-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30040
  type: NodePort