---
- name: Deploy Kubernetes Resources using kubectl
  hosts: localhost
  tasks:
    - name: Apply model-pv
      shell: kubectl apply -f ./k8s/model-pv.yaml
      
    - name: Apply model-pvc
      shell: kubectl apply -f ./k8s/model-pvc.yaml
      
    - name: Apply model-uploader
      shell: kubectl apply -f ./k8s/model-uploader.yaml
      
    - name: Apply cloudinary-secrets
      shell: kubectl apply -f ./k8s/cloudinary-secrets.yaml
      
    - name: Apply configmap
      shell: kubectl apply -f ./k8s/configmap.yaml
      
    - name: Apply backend-service
      shell: kubectl apply -f ./k8s/backend-service.yaml
      
    - name: Apply frontend-service
      shell: kubectl apply -f ./k8s/frontend-service.yaml
      
    - name: Apply backend-deployment
      shell: kubectl apply -f ./k8s/backend-deployment.yaml
      
    - name: Apply frontend-deployment
      shell: kubectl apply -f ./k8s/frontend-deployment.yaml
      
    - name: Apply backend-hpa
      shell: kubectl apply -f ./k8s/backend-hpa.yaml