apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany

  storageClassName: standard

  hostPath:
    path: "/mnt/data/style-transfer-model"
    type: DirectoryOrCreate