- name: Apply Kubernetes manifests using kubectl
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Apply Kubernetes manifest files
      command: kubectl apply -f {{ item }}
      loop:
        - ../k8s/model-pv.yaml
        - ../k8s/model-pvc.yaml
        - ../k8s/model-uploader.yaml
        - ../k8s/cloudinary-secrets.yaml
        - ../k8s/configmap.yaml
        - ../k8s/backend-service.yaml
        - ../k8s/frontend-service.yaml
        - ../k8s/backend-deployment.yaml
        - ../k8s/backend-hpa.yaml
        - ../k8s/frontend-deployment.yaml
      register: kubectl_result
      failed_when: kubectl_result.rc != 0