---
- name: Deploy Kubernetes Resources
  hosts: localhost
  gather_facts: no

  pre_tasks:
    - name: Check if Minikube is running
      command: minikube status --format='{{.Host}}'
      register: minikube_status
      failed_when: false
      changed_when: false

    - name: Start Minikube if not running
      command: minikube start
      register: minikube_start
      when: minikube_status.stdout != "Running"

    - name: Wait for Minikube to be ready
      command: minikube status --format='{{.Host}}'
      register: minikube_ready
      until: minikube_ready.stdout == "Running"
      retries: 30
      delay: 10
      when: minikube_start is defined and minikube_start is changed

  roles:
    - mlflow
    - backend
    - frontend
    - monitoring
