---
- name: Deploy Kubernetes Resources
  hosts: localhost
  gather_facts: false
  
  pre_tasks:
    - name: Set kubectl context to minikube
      command: kubectl config use-context minikube
      
    - name: Check if minikube is running
      command: minikube status
      register: minikube_status
      failed_when: false
      changed_when: false
      
    - name: Start minikube if not running
      command: minikube start
      when: minikube_status.rc != 0

  roles:
    - mlflow
    - backend
    - frontend
    - monitoring