apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-artifacts-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data/mlflow-artifacts
    type: DirectoryOrCreate