apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:latest
        ports:
        - containerPort: 7000
        command:
        - mlflow
        - server
        - --host=0.0.0.0
        - --port=7000
        - --backend-store-uri=sqlite:///mlflow/mlflow.db
        - --default-artifact-root=file:///mlflow/artifacts
        - --serve-artifacts
        volumeMounts:
        - name: mlflow-artifacts
          mountPath: /mlflow/artifacts
        - name: mlflow-db
          mountPath: /mlflow
      volumes:
      - name: mlflow-artifacts
        persistentVolumeClaim:
          claimName: mlflow-artifacts-pvc
      - name: mlflow-db
        persistentVolumeClaim:
          claimName: mlflow-db-pvc